services:
    valkey:
        image: valkey/valkey:9.1
        ports:
            - ${REDIS_PORT:-6379}:6379
        restart: unless-stopped

    postgres:
        image: postgres
        restart: always
        shm_size: 128mb
        env_file:
            - .env
        environment:
            - POSTGRES_PASSWORD
            - POSTGRES_USER
            - POSTGRES_DB
        ports:
            - ${POSTGRES_PORT:-5432}:5432
        volumes:
            - postgres_data:/var/lib/postgresql

    adminer:
        image: adminer
        restart: unless-stopped
        ports:
            - ${ADMINER_PORT:-8080}:8080

volumes:
    postgres_data:
